"""Checkpoint helpers for long-running description scoring runs."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from ..core.config import ScoreDescriptionsConfig
from ..core.io_utils import file_sha256, read_jsonl, write_json_atomic
from ..schema_design.schema_models import RegionFeatureSchema
from .models import DescriptionSegment, SegmentRegionScore

SCORE_ROWS_FILENAME = "segment_region_scores.jsonl"
WARNING_ROWS_FILENAME = "scoring_warnings.jsonl"
PROGRESS_FILENAME = "scoring_progress.json"
FINAL_OUTPUT_FILENAMES = (
    "segment_gt_means.jsonl",
    "tr_features.jsonl",
    "tr_descriptions_readable.jsonl",
    "scoring_metadata.json",
)
GENERATED_SCORING_FILENAMES = (
    SCORE_ROWS_FILENAME,
    WARNING_ROWS_FILENAME,
    PROGRESS_FILENAME,
    *FINAL_OUTPUT_FILENAMES,
)


@dataclass(frozen=True)
class ScoringCheckpoint:
    """Existing checkpoint state loaded before a score-descriptions run."""

    scores: list[SegmentRegionScore]
    warnings: list[dict[str, Any]]
    progress: dict[str, Any] | None

    @property
    def completed_segments(self) -> int:
        """Return the number of score rows already committed to JSONL."""

        return len(self.scores)


def _utc_timestamp() -> str:
    """Return a compact, timezone-aware progress timestamp."""

    return datetime.now(UTC).isoformat(timespec="seconds")


def scoring_output_paths(output_dir: str | Path) -> dict[str, Path]:
    """Return the managed output paths for score-descriptions."""

    root = Path(output_dir)
    return {
        "scores": root / SCORE_ROWS_FILENAME,
        "warnings": root / WARNING_ROWS_FILENAME,
        "progress": root / PROGRESS_FILENAME,
    }


def existing_generated_outputs(output_dir: str | Path) -> list[Path]:
    """List managed scoring output files already present in an output dir."""

    root = Path(output_dir)
    return [
        root / filename
        for filename in GENERATED_SCORING_FILENAMES
        if (root / filename).exists()
    ]


def clear_generated_outputs(output_dir: str | Path) -> None:
    """Remove only files generated by score-descriptions."""

    for path in existing_generated_outputs(output_dir):
        path.unlink()


def ensure_output_policy(output_dir: str | Path, *, resume: bool, overwrite: bool) -> None:
    """Enforce explicit resume/overwrite behavior before scoring starts."""

    if resume and overwrite:
        raise ValueError("--resume and --overwrite cannot be used together.")
    if overwrite:
        clear_generated_outputs(output_dir)
        return
    existing = existing_generated_outputs(output_dir)
    if existing and not resume:
        names = ", ".join(path.name for path in existing)
        raise ValueError(
            "Output directory already contains score-descriptions outputs "
            f"({names}). Use --resume to continue or --overwrite to rerun.",
        )


def build_scoring_run_signature(
    *,
    args: Any,
    cfg: ScoreDescriptionsConfig,
) -> dict[str, Any]:
    """Build the resume signature for inputs and scoring-affecting settings."""

    summary_file = getattr(args, "summary_file", None)
    return {
        "descriptions_sha256": file_sha256(args.descriptions),
        "region_schema_sha256": file_sha256(args.region_schema),
        "summary_file_sha256": file_sha256(summary_file) if summary_file else None,
        "provider": cfg.generation_provider,
        "model": cfg.generation_model,
        "scoring_batch_size": cfg.scoring_batch_size,
        "local_buffer_size": cfg.local_buffer_size,
        "tr_s": cfg.tr_s,
        "alignment": cfg.alignment_strategy,
        "total_trs": getattr(args, "total_trs", None),
        "gt_dir": str(args.gt_dir) if getattr(args, "gt_dir", None) else None,
        "gt_file_pattern": getattr(args, "gt_file_pattern", None),
        "gt_time_column": getattr(args, "gt_time_column", None),
        "gt_emotion_column": getattr(args, "gt_emotion_column", None),
    }


def build_scoring_source_paths(args: Any) -> dict[str, str | None]:
    """Build human-readable source path metadata for progress files."""

    return {
        "descriptions": str(args.descriptions),
        "region_schema": str(args.region_schema),
        "summary_file": (
            str(args.summary_file)
            if getattr(args, "summary_file", None)
            else None
        ),
        "gt_dir": str(args.gt_dir) if getattr(args, "gt_dir", None) else None,
    }


def load_progress(path: str | Path) -> dict[str, Any] | None:
    """Read a progress JSON file when present."""

    progress_path = Path(path)
    if not progress_path.exists():
        return None
    try:
        with progress_path.open("r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Cannot resume: {progress_path} is not valid JSON.") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"Cannot resume: {progress_path} must contain a JSON object.")
    return payload


def validate_progress_signature(
    progress: dict[str, Any] | None,
    run_signature: dict[str, Any],
) -> None:
    """Ensure checkpoint metadata matches the current score-descriptions run."""

    if progress is None:
        return
    previous = progress.get("run_signature")
    if previous != run_signature:
        raise ValueError(
            "Cannot resume: scoring_progress.json does not match the current "
            "inputs or scoring settings. Use the original command or --overwrite.",
        )


def _validate_resume_row(
    *,
    row: dict[str, Any],
    row_idx: int,
    segment: DescriptionSegment,
    schema: RegionFeatureSchema,
    cfg: ScoreDescriptionsConfig,
) -> None:
    """Validate one resumed score row against the current inputs."""

    if row.get("segment_id") is None or row.get("batch_idx") is None:
        raise ValueError(
            "Cannot resume: score rows must contain segment_id and batch_idx.",
        )
    if int(row["segment_id"]) != row_idx:
        raise ValueError("Cannot resume: score rows are not a contiguous prefix.")
    expected_batch_idx = row_idx // cfg.scoring_batch_size
    if int(row["batch_idx"]) != expected_batch_idx:
        raise ValueError("Cannot resume: score rows have inconsistent batch_idx values.")
    if abs(float(row["start_s"]) - segment.start_s) > 1e-6:
        raise ValueError("Cannot resume: score row start time does not match descriptions.")
    if abs(float(row["end_s"]) - segment.end_s) > 1e-6:
        raise ValueError("Cannot resume: score row end time does not match descriptions.")
    if str(row["description"]).strip() != segment.description:
        raise ValueError("Cannot resume: score row description does not match input.")
    scores = row.get("dimension_scores")
    if not isinstance(scores, dict):
        raise ValueError("Cannot resume: score rows must contain dimension_scores objects.")
    if set(scores) != set(schema.ordered_dimension_ids()):
        raise ValueError("Cannot resume: score row dimensions do not match region schema.")


def load_resume_scores(
    *,
    path: str | Path,
    segments: list[DescriptionSegment],
    schema: RegionFeatureSchema,
    cfg: ScoreDescriptionsConfig,
) -> list[SegmentRegionScore]:
    """Load and validate the committed score-row prefix for resume."""

    score_path = Path(path)
    if not score_path.exists():
        return []
    try:
        rows = read_jsonl(score_path)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Cannot resume: {score_path} contains invalid JSONL.") from exc
    if len(rows) > len(segments):
        raise ValueError("Cannot resume: score rows exceed the current segment count.")
    if len(rows) not in (0, len(segments)) and len(rows) % cfg.scoring_batch_size != 0:
        raise ValueError(
            "Cannot resume: score rows end in a partial batch. Use --overwrite "
            "or manually remove the incomplete batch before resuming.",
        )
    for row_idx, row in enumerate(rows):
        _validate_resume_row(
            row=row,
            row_idx=row_idx,
            segment=segments[row_idx],
            schema=schema,
            cfg=cfg,
        )
    return [SegmentRegionScore.from_dict(row) for row in rows]


def load_resume_warnings(path: str | Path) -> list[dict[str, Any]]:
    """Load warning rows already committed by an interrupted run."""

    warning_path = Path(path)
    if not warning_path.exists():
        return []
    try:
        return read_jsonl(warning_path)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Cannot resume: {warning_path} contains invalid JSONL.") from exc


def load_scoring_checkpoint(
    *,
    output_dir: str | Path,
    segments: list[DescriptionSegment],
    schema: RegionFeatureSchema,
    cfg: ScoreDescriptionsConfig,
    run_signature: dict[str, Any],
    resume: bool,
) -> ScoringCheckpoint:
    """Load existing checkpoint state, validating it only for resume runs."""

    paths = scoring_output_paths(output_dir)
    progress = load_progress(paths["progress"])
    if not resume:
        return ScoringCheckpoint(scores=[], warnings=[], progress=progress)
    if progress is None and existing_generated_outputs(output_dir):
        raise ValueError(
            "Cannot resume: score-descriptions outputs exist but "
            "scoring_progress.json is missing.",
        )
    validate_progress_signature(progress, run_signature)
    return ScoringCheckpoint(
        scores=load_resume_scores(
            path=paths["scores"],
            segments=segments,
            schema=schema,
            cfg=cfg,
        ),
        warnings=load_resume_warnings(paths["warnings"]),
        progress=progress,
    )


def build_progress_payload(
    *,
    status: str,
    total_segments: int,
    completed_segments: int,
    cfg: ScoreDescriptionsConfig,
    run_signature: dict[str, Any],
    source_paths: dict[str, str | None],
    warning_summary: dict[str, Any],
) -> dict[str, Any]:
    """Build the serialized checkpoint progress payload."""

    completed_batches = 0
    if completed_segments:
        completed_batches = (completed_segments + cfg.scoring_batch_size - 1) // cfg.scoring_batch_size
    return {
        "command": "score-descriptions",
        "status": status,
        "updated_at": _utc_timestamp(),
        "total_segments": total_segments,
        "completed_segments": completed_segments,
        "next_segment_id": min(completed_segments, total_segments),
        "completed_batches": completed_batches,
        "scoring_batch_size": cfg.scoring_batch_size,
        "local_buffer_size": cfg.local_buffer_size,
        "provider": cfg.generation_provider,
        "model": cfg.generation_model,
        "run_signature": run_signature,
        "source_paths": source_paths,
        "scoring_warnings": warning_summary,
    }


def write_progress(path: str | Path, payload: dict[str, Any]) -> None:
    """Persist progress metadata atomically."""

    write_json_atomic(path, payload)
